In [2]:
import numpy as np

# Basic

In [24]:
a=np.array([1,2,3], dtype="int16")
print(a)

[1 2 3]


In [16]:
b = np.array([[9.0,8.0,7.0],[6.0,4.0,3.0]])
print(b)

[[9. 8. 7.]
 [6. 4. 3.]]


In [18]:
#Get dimension
a.ndim

1

In [20]:
#Get shape
b.shape

(2, 3)

In [25]:
#Get type
a.dtype

dtype('int16')

In [30]:
#Get Size (item contain how many byte)
a.itemsize

2

In [29]:
#Get total size
a.nbytes

6

# Access/Change specific elements, rows, columns, etc

In [32]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,12,13,14,15]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 12 13 14 15]]


In [34]:
#get a specific item [r,c]
a[1,5]

14

In [36]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
#get a specific column
a[:,2]

array([ 3, 10])

In [41]:
#get fancy[startindex : endindex(exclusive) : stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [43]:
a[1,5]=20
print (a)

a[:,2] = [13,19]
a[:,0]=0
print(a)

[[ 1  2 13  4  5  6  7]
 [ 8  9 19 12 13 20 15]]
[[ 0  2 13  4  5  6  7]
 [ 0  9 19 12 13 20 15]]


In [46]:
#3-d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [48]:
print(b[0,1,1])

4


# Initializing different types of array

In [51]:
#all zero matrix
np.zeros((2,4,3,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [73]:
#all ones
np.ones((3,4,5),dtype="int32")

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int32)

In [75]:
#identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
#other value
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [63]:
#copy pattern
print(a)
print(a.shape)
print("")

print(np.full_like(a.shape, 4))
print("")
print(np.full_like(a, 4))

[[ 0  2 13  4  5  6  7]
 [ 0  9 19 12 13 20 15]]
(2, 7)

[4 4]

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [65]:
#random decimal 0-1
np.random.rand(4,2,3)

array([[[0.63605641, 0.56711022, 0.60067007],
        [0.77964892, 0.12630618, 0.79756762]],

       [[0.82917702, 0.83972733, 0.80865332],
        [0.95620867, 0.42337243, 0.38763622]],

       [[0.23851878, 0.83086606, 0.98130471],
        [0.39465054, 0.68494378, 0.06104017]],

       [[0.45766007, 0.91945351, 0.87955233],
        [0.75986866, 0.77852778, 0.08415397]]])

In [72]:
# random inetger value
np.random.randint(0,100,size=(3,3))

array([[50, 17, 80],
       [39, 28, 85],
       [ 8, 17,  2]])

In [84]:
#Repeat
arr=np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
print(r1,"\n")

r2= np.repeat(arr,3,axis=0)
print(r2)

[[1 1 1 2 2 2 3 3 3]] 

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [86]:
output = np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [91]:
a=np.array([1,2,3])
b=a                 #連立
c=np.array([1,2,3])
d=c.copy()         #純copy content

b[0]=100
print(a)
print(b)
c[0]=100
print(c)
print(d)

[100   2   3]
[100   2   3]
[100   2   3]
[1 2 3]


# Mathematics

In [92]:
a=np.array([1,2,3,4])

In [97]:
print(a+2)
print(a-2)
print(a*2)
print(a+2)
print(a+a)
print(a**2)
print(np.sin(a))

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[3 4 5 6]
[2 4 6 8]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [98]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

# Linear Algebra

In [103]:
a= np.ones((2,3))
print(a)

b= np.full((3,2),3)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]
 [3 3]]


array([[9., 9.],
       [9., 9.]])

In [106]:
#find lin(ear) alg(ebra) zdeterminant
c = np.identity(3)
np.linalg.det(c)

1.0

In [108]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Statistics

In [111]:
stat = np.array([[1,2,3],[4,5,6]])
stat

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
np.min(stat, axis=1) #1 for 0 for

array([1, 4])

In [117]:
np.max(stat)

6

# Organize an array

In [122]:
before = np.array([[1,2,3,4],[5,6,7,8]])

after= before.reshape((2,2,2)) #2,2,2 is equal to 8

after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [125]:
#Vertically/Horizontally stacking vectors
v1 = np.array([1,2,3,4])
v2= np.array([5,6,7,8])

print(np.vstack([v1,v2,v1,v2]))
print(np.hstack([v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]


# Miscellaneous

In [141]:
#load file
filedata=np.genfromtxt("Np_practice_data1", delimiter=",", dtype="int32")
print(filedata)

print('\n"different approach"\n')
filedata2=np.genfromtxt("Np_practice_data1", delimiter=",")
filedata2= filedata2.astype("int32")
print(filedata2)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]

"different approach"

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [153]:
#Boolean Masking and advanced indexing
print(filedata>50)
print("\nReverse\n")
print(~(filedata>50)) #~ to reverse the boolean value

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]

Reverse

[[ True  True  True  True False False  True  True  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True False False  True False  True  True  True  True
   True  True  True  True  True  True]
 [ True  True  True  True False  True  True  True False  True  True  True
   True  True  True  True False False]]


In [146]:
filedata2[filedata2 >50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [148]:
a=np.array([1,2,3,4,5,6,7,8,9,10,12,13,14,15])
a[[1,3,6]] #as a list indexing

array([2, 4, 7])

In [150]:
np.any(filedata2 >50, axis=0)
#axis=0 in a column to check
#acis=1 in a row to check as a whole

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [2]:
from IPython.display import Image
Image(filename="WechatIMG1611.jpeg") 

In [3]:
#0 row select index 1 item
#...